In a 10x10 confusion matrix the values for True Positive, True Negative and False Positive, False Negative are a bit more confusingly placed than those regarding a simpler binary classification task. 
</br>
**True_Positive** : Is the singular value regarding a class label. For example, for class 6, the True Positive value is the cell at indices [5,5].
</br>
**True_Negative** : Is everything else on the confusion matrix that isn't on the line and column of the True Positive Value. In our specific example, everything except row 5 and column 5 is part of True Negative and has to be sum'ed.
</br>
**False_Positive** : Everything on the previously ignored column (with the exception of the correct value for TP) is called False Positive.
</br>
**False_Negative** : Everything on the previously ignored row  (with the exception of the value for TP) is called False Negative.

*As it might have become obvious by now, we have to calculate all these scores for all of the 10 classes in our dataset. That means each class will in the end have their own PRecision, Recall and F1-score.*

In [1]:
import pandas as pd
import numpy as np

df = pd.read_parquet(path=r'C:\Users\Noel\Documents\THESIS\Feature Visualization\dataframe_test65')
# print(df)

conf_mat = df.to_numpy()
print(conf_mat)
Mean_Acc = 0
for i in range(len(conf_mat)):
    Mean_Acc += conf_mat[i, i] / 1000
print(f"Mean Accuracy: {(Mean_Acc * 10):.4f} %")
class_score_dict = {}
for class_label in range(len(conf_mat)):

    TP = conf_mat[class_label, class_label]
    temp_conf = np.copy(conf_mat)
    temp_conf[class_label, class_label] = 0
    FP = sum(temp_conf[:, class_label])
    FN = sum(temp_conf[class_label, :])

    temp_conf = np.copy(conf_mat)
    temp_conf[:, class_label] = 0
    temp_conf[class_label, :] = 0

    TN = sum(sum(temp_conf))
    # TN = np.mean(temp_conf)  # Same operation...
    

    # Calculate scores and save them to dictionary
    Precision = TP / (TP + FP)
    Recall = TP / (TP + FN)
    F1 = (Precision * Recall / (Precision + Recall)) * 2 

    class_score_dict[class_label] = (Precision, Recall, F1)

for key, value in class_score_dict.items():
    print(f'Class {key}: Precision:{value[0]:.4f}, Recall:{value[1]:.4f}, F1-Score:{value[2]:.4f}')

[[666   8  50  33  70  54  16  44  43  16]
 [ 10 774   3   6   3  34  90  71   9   0]
 [112  18 479  60 157  47  13  21  90   3]
 [ 32  15  55 462 203 159  14  51   8   1]
 [ 65   8 139 137 514  64  10  23  37   3]
 [ 46  56  32 121  62 485  27 148  23   0]
 [ 21 130  10   4   5  17 762  34  17   0]
 [ 40 111  18  54  13 169  33 527  30   5]
 [ 57   9  91  10  18  23  19  13 757   3]
 [ 28   1   2   0   1   1   2   1   3 961]]
Mean Accuracy: 63.8700 %
Class 0: Precision:0.6184, Recall:0.6660, F1-Score:0.6413
Class 1: Precision:0.6850, Recall:0.7740, F1-Score:0.7268
Class 2: Precision:0.5449, Recall:0.4790, F1-Score:0.5098
Class 3: Precision:0.5209, Recall:0.4620, F1-Score:0.4897
Class 4: Precision:0.4914, Recall:0.5140, F1-Score:0.5024
Class 5: Precision:0.4606, Recall:0.4850, F1-Score:0.4725
Class 6: Precision:0.7728, Recall:0.7620, F1-Score:0.7674
Class 7: Precision:0.5648, Recall:0.5270, F1-Score:0.5453
Class 8: Precision:0.7443, Recall:0.7570, F1-Score:0.7506
Class 9: Precision:0.9